"""Generate concrete model registrations from the approved v0.2 catalog."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=json.loads((root.parent/'v02/design.json').read_text())
cards=data['cards']+data['tokens']
damage={'B01':(6,9),'B03':(5,8),'C01':(9,12),'C02':(5,7),'C06':(7,10),'C08':(8,11),'C15':(4,5),'C16':(8,11),'C17':(7,10),'C20':(7,10),'U06':(16,20),'U07':(12,16),'U13':(4,7),'U14':(12,16),'U22':(7,10),'U26':(6,8),'R05':(9,12),'R06':(7,9),'R11':(12,16)}
block={'B02':(5,8),'B04':(7,10),'C03':(6,9),'C04':(5,8),'C07':(5,8),'C09':(8,11),'C14':(3,5),'C18':(5,8),'C19':(4,6),'U05':(4,7),'U09':(4,7),'U15':(8,11),'U19':(5,8),'U21':(7,10),'U27':(7,10),'U28':(6,9),'R07':(20,26),'R10':(6,9),'T01':(6,9)}
targeted=set('B01 B03 C01 C02 C04 C05 C06 C07 C08 C10 C15 C16 C20 U01 U06 U07 U10 U12 U13 U14 U15 U22 U26 R05 R06 T02'.split())
area={'C17','C18','U11','R11'}
for code,name,text in [('Q00','不支付','不支付生命。'),('Q02','支付2生命','额外造成4点伤害。'),('Q04','支付4生命','额外造成8点伤害。'),('QIC','进入冰','进入冰形态。'),('QMO','进入月','进入月形态。')]:
    cards.append(dict(id=code,name=name,type='技能',rarity='衍生',cost=0,up_cost=0,base=text,upgraded=text))
q=lambda s:json.dumps(s,ensure_ascii=False)
out=['// Generated by tools/generate_cards.py. Edit the v0.2 catalog or generator, not this file.','namespace Frostmoon;','public static class CardCatalog {','public static readonly Dictionary<string,CardDefinition> All = new() {']
for c in cards:
    id=c['id'];d=damage.get(id,(0,0));b=block.get(id,(0,0));type={'攻击':'Attack','技能':'Skill','能力':'Power'}[c['type']];rarity={'初始':'Basic','普通':'Common','罕见':'Uncommon','稀有':'Rare','衍生':'Token'}[c['rarity']]
    target='AnyEnemy' if id in targeted else 'AllEnemies' if id in area else 'Self'
    cost=c['cost'] if isinstance(c['cost'],int) else 0;upcost=c['up_cost'] if isinstance(c['up_cost'],int) else 0
    vals=[q(id),q(c['name']),str(cost),str(upcost),f'CardType.{type}',f'CardRarity.{rarity}',f'TargetType.{target}',q(c['base']),q(c['upgraded']),*map(str,[*d,*b]),str('保留' in c['base']).lower(),str('消耗' in c['base']).lower()]
    out.append(f'[{q(id)}] = new('+','.join(vals)+'),')
out+=['};','public static CardDefinition Get(string code)=>All[code];','public static CardModel Canonical(string code)=>ModelDb.GetById<CardModel>(ModelDb.GetId(Type.GetType("Frostmoon.Fm"+code)!));','public static PowerModel Ability(string code)=>ModelDb.GetById<PowerModel>(ModelDb.GetId(Type.GetType("Frostmoon.Ability"+code)!));']
out+=['public static readonly (string Code,bool Up)[][] Presets = [']
for deck in data['decks']:
    entries=[f'({q(e["id"])},{str(e["upgrade"]).lower()})' for e in deck['entries'] for _ in range(e['count'])]
    out.append('['+','.join(entries)+'],')
out+= ['];','}']
for c in cards:
    id=c['id'];out.append(f'[Pool(typeof(FrostmoonCardPool))] public class Fm{id} : FrostmoonCard {{ public override string Code => "{id}"; public Fm{id}():base("{id}"){{}} }}')
    if c['type']=='能力':out.append(f'public class Ability{id} : FrostmoonAbility {{ public override string Code => "{id}"; }}')
(root/'src/Catalog.g.cs').write_text('\n'.join(out)+'\n')
print(f'Generated {len(data["cards"])} cards, {len(data["tokens"])} tokens and 5 choice models.')
